const posts = [
    {
        id: 1,
        img: "https://www.nature.org/content/dam/tnc/nature/en/photos/tnc_48980557.jpg",
        heading: "Wherever far wow thus a squirrel raccoon jeez jaguar this from along",
        date: "JUNE 25, 2020",
        category: "ART",
        details: "The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word \"and\" and the Little Blind",
    },
    {
        id: 2,
        img: "https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/FreeFlowingRiver.jpg?crop=191,0,1322,992&wid=820&hei=615&scl=1.6130081300813008",
        heading: "Coffe sugar, chicory seasonal espresso barista americano",
        date: "JUNE 25, 2020",
        category: "MUSIC",
        details: "Arista, percolator, cream, aromatic, fair trade, breve body instant lungo blue mountain cappuccino. Americano aroma mug espresso latte crema milk redeye acerbic. Galão robusta instant, decaffeinated, so fair trade wings.",
    },
    {
        id: 3,
        img: "https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/robert-keane-1425463-unsplash.jpg?crop=0,0,3556,2667&wid=820&hei=615&scl=4.336585365853659",
        heading: "According a funnily until pre-set or arrogant well cheerful",
        date: "JUNE 25, 2020",
        category: "COFFE",
        details: "Single shot cultivar beans as chicory caffeine. Medium brewed, milk extra that froth pumpkin spice mocha. Whipped redeye pumkin spice sweet, extraction to go macchiato acerbic steamed filter. Robusta grounds decaffeinated.",
    },
    {
        id: 4,
        img: "https://images.hdqwalls.com/download/best-nature-image-1440x900.jpg",
        heading: "Overlaid the jeepers uselessly much excluding",
        date: "JUNE 25, 2020",
        category: "ART",
        details: "Far far away, behind the word mountains, far from the countris Vokalia and Consonatia, there live the blined texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
    },
    {
        id: 5,
        img: "https://sites.google.com/site/beautyofnature98/_/rsrc/1482911355882/config/customLogo.gif?revision=1",
        heading: "Coffee variety macchiato, as organic ut variety caffeine americano",
        date: "JUNE 25, 2020",
        category: "MUSIC",
        details: "Saucer, crema carajillo, bar, mocha medium, latte cappucchino and espresso acerbic to go. Coffe, irish foam turkish coffe blue mountain seasonal. Turkish grinder medium, plunger pot, coffe viennese crema galão macchiato.",
    },
    {
        id: 6,
        img: "https://www.nature.org/content/dam/tnc/nature/en/photos/tnc_48980557.jpg",
        heading: "Wherever far wow thus a squirrel raccoon jeez jaguar this from along",
        date: "JUNE 25, 2020",
        category: "COFFE",
        details: "The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word \"and\" and the Little Blind",
    },
    {
        id: 7,
        img: "https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/FreeFlowingRiver.jpg?crop=191,0,1322,992&wid=820&hei=615&scl=1.6130081300813008",
        heading: "Coffe sugar, chicory seasonal espresso barista americano",
        date: "JUNE 25, 2020",
        category: "ART",
        details: "Arista, percolator, cream, aromatic, fair trade, breve body instant lungo blue mountain cappuccino. Americano aroma mug espresso latte crema milk redeye acerbic. Galão robusta instant, decaffeinated, so fair trade wings.",
    },
    {
        id: 8,
        img: "https://natureconservancy-h.assetsadobe.com/is/image/content/dam/tnc/nature/en/photos/robert-keane-1425463-unsplash.jpg?crop=0,0,3556,2667&wid=820&hei=615&scl=4.336585365853659",
        heading: "According a funnily until pre-set or arrogant well cheerful",
        date: "JUNE 25, 2020",
        category: "MUSIC",
        details: "Single shot cultivar beans as chicory caffeine. Medium brewed, milk extra that froth pumpkin spice mocha. Whipped redeye pumkin spice sweet, extraction to go macchiato acerbic steamed filter. Robusta grounds decaffeinated.",
    },
    {
        id: 9,
        img: "https://images.hdqwalls.com/download/best-nature-image-1440x900.jpg",
        heading: "Overlaid the jeepers uselessly much excluding",
        date: "JUNE 25, 2020",
        category: "COFFE",
        details: "Far far away, behind the word mountains, far from the countris Vokalia and Consonatia, there live the blined texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
    },
    {
        id: 10,
        img: "https://sites.google.com/site/beautyofnature98/_/rsrc/1482911355882/config/customLogo.gif?revision=1",
        heading: "Coffee variety macchiato, as organic ut variety caffeine americano",
        date: "JUNE 25, 2020",
        category: "ART",
        details: "Saucer, crema carajillo, bar, mocha medium, latte cappucchino and espresso acerbic to go. Coffe, irish foam turkish coffe blue mountain seasonal. Turkish grinder medium, plunger pot, coffe viennese crema galão macchiato.",
    },
]

export default posts